# Generated by Django 3.1.5 on 2021-01-18 14:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name': '끝에 s가붙을거다.vervose_name ', 'verbose_name_plural': '끝에 s가안붙는다.vervose_plural'},
        ),
        migrations.RenameField(
            model_name='members',
            old_name='useremail',
            new_name='user_email',
        ),
        migrations.AddField(
            model_name='members',
            name='update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='수정일시'),
            preserve_default=False,
        ),
    ]
